### ISSUE TITLE
cannot run stardist from CLI through script+project

### ISSUE THREAD

**Issue by MishalAshraf** [qupath/qupath-extension-stardist#26]
Hello! 

When I try to use CLI to run an image processing task involving stardist I get the following error. It seems the workflow correctly loads stardist for the first call (as I am guessing from the "Added extension" line). Yet, on subsequent calls, I think something in the way batching works for scripts makes it lose track of where the Stardist installation lives. 

>"QuPath-0.3.2 (console).lnk" script -p="C:\Users\mashraf\Documents\QP_MAKEPROJ3\QuPathProject\project.qpproj" -s "C:\Users\mashraf\qp_batch_bash\da_stardist_v3_reg.groovy"

OpenJDK 64-Bit Server VM warning: Option --illegal-access is deprecated and will be removed in a future release.
15:38:46.089 [main] [INFO ] qupath.lib.common.ThreadTools - Setting parallelism to 15
15:38:46.256 [main] [INFO ] qupath.ScriptCommand - Setting tile cache size to 32600.00 MB (25.0% max memory)
15:38:46.366 [main] [INFO ] qupath.lib.gui.ExtensionClassLoader - Refreshing extensions in C:\Users\mashraf\Documents\qp_ext_test\extensions
15:38:46.367 [main] [INFO ] qupath.lib.gui.ExtensionClassLoader - Added extension: C:\Users\mashraf\Documents\qp_ext_test\extensions\qupath-extension-stardist-0.3.2.jar
15:38:46.381 [main] [INFO ] qupath.lib.scripting.QP - Initializing type adapters
15:38:47.761 [main] [INFO ] qupath.ScriptCommand - Running script for 2022_02_22__14_20__1786-Extended Depth of Focus-07-Scene-1-ScanRegion0_crop.czi - Scene #1
15:38:47.804 [main] [INFO ] q.l.i.s.o.OpenslideServerBuilder - OpenSlide version 3.4.1
15:38:47.926 [main] [INFO ] q.l.i.s.b.BioFormatsServerOptions - Setting max Bio-Formats readers to 16
C:\Users\mashraf\OneDrive - bluerocktx\Documents\qp_ext_test
15:38:56.479 [ForkJoinPool.commonPool-worker-25] [WARN ] qupath.opencv.ops.ImageOps - Normalization percentiles give the same value (0.0), scale will be Infinity
15:38:56.485 [ForkJoinPool.commonPool-worker-7] [WARN ] qupath.opencv.ops.ImageOps - Normalization percentiles give the same value (0.0), scale will be Infinity
15:38:56.635 [ForkJoinPool.commonPool-worker-13] [WARN ] qupath.opencv.ops.ImageOps - Normalization percentiles give the same value (0.0), scale will be Infinity
15:38:56.652 [ForkJoinPool.commonPool-worker-19] [WARN ] qupath.opencv.ops.ImageOps - Normalization percentiles give the same value (0.0), scale will be Infinity
15:38:56.861 [ForkJoinPool.commonPool-worker-23] [WARN ] qupath.opencv.ops.ImageOps - Normalization percentiles give the same value (0.0), scale will be Infinity
15:38:57.274 [ForkJoinPool.commonPool-worker-31] [WARN ] qupath.opencv.ops.ImageOps - Normalization percentiles give the same value (0.0), scale will be Infinity
15:38:59.955 [ForkJoinPool.commonPool-worker-1] [WARN ] qupath.opencv.ops.ImageOps - Normalization percentiles give the same value (0.0), scale will be Infinity
15:39:01.089 [ForkJoinPool.commonPool-worker-23] [WARN ] qupath.opencv.ops.ImageOps - Normalization percentiles give the same value (0.0), scale will be Infinity
15:39:04.608 [ForkJoinPool.commonPool-worker-9] [WARN ] qupath.opencv.ops.ImageOps - Normalization percentiles give the same value (0.0), scale will be Infinity
15:39:13.733 [main] [WARN ] qupath.lib.scripting.QP - Cannot run object classifier - no names provided!
15:39:13.745 [main] [INFO ] qupath.lib.io.PathIO - Writing object hierarchy with 1128 object(s)...
15:39:13.776 [main] [INFO ] qupath.lib.io.PathIO - Image data written in 0.04 seconds
15:39:13.819 [main] [INFO ] qupath.ScriptCommand - Running script for 2022_02_22__14_20__1786-Extended Depth of Focus-07-Scene-2-ScanRegion1_crop.czi - Scene #1
It looks like you have tried to import a class 'qupath.ext.stardist.StarDist' that doesn't exist!
MultipleCompilationErrorsException at line 11: startup failed:
Script2.groovy: 12: unable to resolve class qupath.ext.stardist.StarDist2D
 @ line 12, column 1.
   import qupath.ext.stardist.StarDist2D
   ^

1 error

org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:295)
    org.codehaus.groovy.control.CompilationUnit$ISourceUnitOperation.doPhaseOperation(CompilationUnit.java:914)
    org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:627)
    groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:389)
    groovy.lang.GroovyClassLoader.lambda$parseClass$3(GroovyClassLoader.java:332)
    org.codehaus.groovy.runtime.memoize.StampedCommonCache.compute(StampedCommonCache.java:163)
    org.codehaus.groovy.runtime.memoize.StampedCommonCache.getAndPut(StampedCommonCache.java:154)
    groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:330)
    groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:314)
    groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:257)
    org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.getScriptClass(GroovyScriptEngineImpl.java:336)
    org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:153)
    qupath.lib.gui.scripting.DefaultScriptEditor.executeScript(DefaultScriptEditor.java:982)
    qupath.ScriptCommand.runScript(QuPath.java:432)
    qupath.ScriptCommand.run(QuPath.java:319)
    picocli.CommandLine.executeUserObject(CommandLine.java:1939)
    picocli.CommandLine.access$1300(CommandLine.java:145)
    picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
    picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
    picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
    picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
    picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
    picocli.CommandLine.execute(CommandLine.java:2078)
    qupath.QuPath.main(QuPath.java:187)
15:39:14.114 [main] [ERROR] qupath.ScriptCommand - Error running script for image: 2022_02_22__14_20__1786-Extended Depth of Focus-07-Scene-2-ScanRegion1_crop.czi - Scene #1
javax.script.ScriptException: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
Script2.groovy: 12: unable to resolve class qupath.ext.stardist.StarDist2D
 @ line 12, column 1.
   import qupath.ext.stardist.StarDist2D
   ^

1 error

        at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:158)
        at qupath.lib.gui.scripting.DefaultScriptEditor.executeScript(DefaultScriptEditor.java:982)
        at qupath.ScriptCommand.runScript(QuPath.java:432)
        at qupath.ScriptCommand.run(QuPath.java:319)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at qupath.QuPath.main(QuPath.java:187)
Caused by: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
Script2.groovy: 12: unable to resolve class qupath.ext.stardist.StarDist2D
 @ line 12, column 1.
   import qupath.ext.stardist.StarDist2D

This error repeats a bunch of times, sometimes with the "Script2.groovy" section incrementing (although not in all cases). I should add that when I run the same script through the GUI it works just fine. Wondering if there is any way to force the batching to keep my extension path locked in? Open to any other solutions as well.

Thanks,

Mishal

**Comment by MishalAshraf** [comment]
I should add that I have tried this both in linux and windows and have ended up with similar issues.

**Comment by petebankhead** [comment]
Hi @MishalAshraf have you tried this with the latest very of QuPath (v0.4.1) and the latest StarDist extension?

I see the bug report mentions QuPath v0.3.2 but some things that may be relevant have already been fixed.

**Comment by MishalAshraf** [comment]
`C:\Apps\QuPath-0.4.1>"QuPath-0.4.1` (console).exe" script -p="C:\Users\mashraf\Documents\qp40_makeproj\QuPathProject\project.qpproj" -s "C:\Users\mashraf\qp_batch_bash\da_stardist_v3_reg.groovy"`
10:57:33.991 [main] [INFO ] qupath.lib.common.ThreadTools - Setting parallelism to 15
10:57:34.007 [main] [INFO ] qupath.lib.gui.prefs.PathPrefs - Setting default Locale to en_US
10:57:34.008 [main] [INFO ] qupath.lib.gui.prefs.PathPrefs - Setting Locale for FORMAT to en_US
10:57:34.009 [main] [INFO ] qupath.lib.gui.prefs.PathPrefs - Setting Locale for DISPLAY to en_US
10:57:34.038 [main] [INFO ] qupath.ScriptCommand - Setting tile cache size to 32600.00 MB (25.0% max memory)
10:57:34.126 [main] [INFO ] qupath.lib.gui.ExtensionClassLoader - Refreshing extensions in C:\Users\mashraf\Documents\qupath_041_userpath\extensions
10:57:34.127 [main] [INFO ] qupath.lib.gui.ExtensionClassLoader - Added extension: C:\Users\mashraf\Documents\qupath_041_userpath\extensions\qupath-extension-stardist-0.4.0.jar
10:57:34.141 [main] [INFO ] qupath.lib.scripting.QP - Initializing type adapters
10:57:35.350 [main] [INFO ] qupath.ScriptCommand - Running script for 2022_02_22__14_20__1786-Extended Depth of Focus-07-Scene-1-ScanRegion0_crop.czi - Scene #1 (0/1221)
10:57:35.421 [main] [INFO ] q.l.i.s.o.OpenslideServerBuilder - OpenSlide version 3.4.1
10:57:35.495 [main] [INFO ] q.l.i.s.b.BioFormatsServerOptions - Bio-Formats memoization is turned OFF (based on Java 17.0.5+8, Bio-Formats 6.11.1)
10:57:35.553 [main] [INFO ] q.l.i.s.b.BioFormatsServerOptions - Setting max Bio-Formats readers to 16
ERROR: It looks like you've tried to import a class 'qupath.ext.stardist.StarDist' that couldn't be found

10:57:38.465 [main] [ERROR] qupath.ScriptCommand - Error running script for image: 2022_02_22__14_20__1786-Extended Depth of Focus-07-Scene-1-ScanRegion0_crop.czi - Scene #1
javax.script.ScriptException: startup failed:
da_stardist_v3_reg.groovy: 14: unable to resolve class qupath.ext.stardist.StarDist2D
 @ line 13, column 1.
   import qupath.ext.stardist.StarDist2D
   ^

1 error
 in da_stardist_v3_reg.groovy at line number 13
        at qupath.lib.gui.scripting.languages.DefaultScriptLanguage.execute(DefaultScriptLanguage.java:311)
        at qupath.ScriptCommand.runBatchScript(QuPath.java:491)
        at qupath.ScriptCommand.run(QuPath.java:359)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at qupath.QuPath.main(QuPath.java:196)
Caused by: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
da_stardist_v3_reg.groovy: 14: unable to resolve class qupath.ext.stardist.StarDist2D
 @ line 14, column 1.
   import qupath.ext.stardist.StarDist2D
   ^

1 error

        at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:292)
        at org.codehaus.groovy.control.CompilationUnit$ISourceUnitOperation.doPhaseOperation(CompilationUnit.java:909)
        at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:692)
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:666)
        at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:373)
        at groovy.lang.GroovyClassLoader.lambda$parseClass$2(GroovyClassLoader.java:316)
        at org.codehaus.groovy.runtime.memoize.StampedCommonCache.compute(StampedCommonCache.java:163)
        at org.codehaus.groovy.runtime.memoize.StampedCommonCache.getAndPut(StampedCommonCache.java:154)
        at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:314)
        at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:298)
        at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:258)
        at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.getScriptClass(GroovyScriptEngineImpl.java:350)
        at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:159)
        at qupath.lib.gui.scripting.languages.DefaultScriptLanguage.execute(DefaultScriptLanguage.java:233)
        ... 11 common frames omitted
10:57:38.481 [main] [INFO ] qupath.ScriptCommand - Running script for 2022_02_22__14_20__1786-Extended Depth of Focus-07-Scene-2-ScanRegion1_crop.czi - Scene #1 (1/1221)
ERROR: It looks like you've tried to import a class 'qupath.ext.stardist.StarDist' that couldn't be found

10:57:38.779 [main] [ERROR] qupath.ScriptCommand - Error running script for image: 2022_02_22__14_20__1786-Extended Depth of Focus-07-Scene-2-ScanRegion1_crop.czi - Scene #1
javax.script.ScriptException: startup failed:
da_stardist_v3_reg.groovy: 14: unable to resolve class qupath.ext.stardist.StarDist2D
 @ line 13, column 1.
   import qupath.ext.stardist.StarDist2D
   ^

1 error
 in da_stardist_v3_reg.groovy at line number 13
        at qupath.lib.gui.scripting.languages.DefaultScriptLanguage.execute(DefaultScriptLanguage.java:311)
        at qupath.ScriptCommand.runBatchScript(QuPath.java:491)
        at qupath.ScriptCommand.run(QuPath.java:359)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at qupath.QuPath.main(QuPath.java:196)
Caused by: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
da_stardist_v3_reg.groovy: 14: unable to resolve class qupath.ext.stardist.StarDist2D
 @ line 14, column 1.
   import qupath.ext.stardist.StarDist2D
   ^

1 error

        at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:292)
        at org.codehaus.groovy.control.CompilationUnit$ISourceUnitOperation.doPhaseOperation(CompilationUnit.java:909)
        at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:692)
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:666)
        at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:373)
        at groovy.lang.GroovyClassLoader.lambda$parseClass$2(GroovyClassLoader.java:316)
        at org.codehaus.groovy.runtime.memoize.StampedCommonCache.compute(StampedCommonCache.java:163)
        at org.codehaus.groovy.runtime.memoize.StampedCommonCache.getAndPut(StampedCommonCache.java:154)
        at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:314)
        at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:298)
        at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:258)
        at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.getScriptClass(GroovyScriptEngineImpl.java:350)
        at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:159)
        at qupath.lib.gui.scripting.languages.DefaultScriptLanguage.execute(DefaultScriptLanguage.java:233)
        ... 11 common frames omitted
10:57:38.781 [main] [INFO ] qupath.ScriptCommand - Running script for 2022_02_22__14_20__1786-Extended Depth of Focus-07-Scene-2-ScanRegion1_crop.czi - Scene #2 (2/1221)
ERROR: It looks like you've tried to import a class 'qupath.ext.stardist.StarDist' that couldn't be found

**Comment by MishalAshraf** [comment]
Similar error, does not even work on first pass. It also switches to "ERROR: It looks like you've tried to import a class 'qupath.ext.stardist.StarDist' that couldn't be found" in some lines as opposed to StarDist2D in others. Perhaps a hint there. Any suggestion as to how I might be able to get this working properly?

**Comment by petebankhead** [comment]
Can you post the script da_stardist_v3_reg.groovy please?

**Comment by MishalAshraf** [comment]
[da_stardist_v3_reg.txt](https://github.com/qupath/qupath-extension-stardist/files/10403648/da_stardist_v3_reg.txt)
Yup. Had to change from .groovy to .txt to allow uploads, but same file.

**Comment by petebankhead** [comment]
Thanks @MishalAshraf I think I've got a fix for it at
* https://github.com/qupath/qupath/pull/1212

It will require a new QuPath v0.4.2 release - I hope to make one within the next week or so. The extension jar shouldn't need changes for this to work.

**Comment by MishalAshraf** [comment]
Sounds great, looking forward to it! Thanks for your work and help with this.

**Comment by petebankhead** [comment]
QuPath v0.4.2 has just been released - I hope that solves it, if not feel free to reopen the issue

**Comment by MishalAshraf** [comment]
Just confirming that this works with QuPath 0.4.2 running stardist from CLI.

**Comment by petebankhead** [comment]
Wonderful, thanks!
